
const SET_LOGIN = "SET_LOGIN";
const LOGOUT = "LOGOUT";
const GET_CATEGORIES = "GET_CATEGORIES";
const GET_QUIZ = "GET_QUIZ";
const LEAVE_QUIZ = "LEAVE_QUIZ";


export { SET_LOGIN, LOGOUT, GET_CATEGORIES, GET_QUIZ, LEAVE_QUIZ };